### PR TITLE
use v6 CLI

### PR DESCRIPTION
**Pull request by dickeyxxx**

### CODE REVIEW

**Comment by ian-axelrod** [comment]
```
-----> Installing Heroku Client....
gzip: stdin: not in gzip format
tar: Child died with signal 13
tar: Error is not recoverable: exiting now
 !     Push rejected, failed to compile Deployer app.
 !     Push failed
```

I can push a fix to that.

**Comment by dickeyxxx** [comment]
you can use xz or gzip

**Comment by ian-axelrod** [comment]
Yussss. I made a few changes and it is working! Thank you very much.

**Comment by dickeyxxx** [comment]
glad to hear it! hopefully your build times and slug size have gone down a bit!

**Pull request merged**
